services:
  mysql:
    image: mysql:8.0
    container_name: leadfinder-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: